### ISSUE TITLE
Adding LED support to the BLE demo hangs the program.

### ISSUE THREAD

**Issue by pbauszat** [NessieCircuits/Riotee_SDK#17] opened 2024-01-16 11:23 UTC
After extending the BLE demo to blink an LED during the working cycle, the program operates for a few seconds then seems to hang and does not recover anymore.

Source code:
```
#include "riotee.h"
#include "riotee_ble.h"
#include "riotee_gpio.h"
#include "riotee_timing.h"

// <---- NEW LINE
#define TOGGLE_LED PIN_LED_CTRL
// --->

const uint8_t adv_address[] = {0x01, 0xEE, 0xC0, 0xFF, 0x03, 0x02};
const char adv_name[] = "RIOTEE";

static struct {
  unsigned int counter;
} ble_data;

void reset_callback(void) {
  riotee_ble_init();
  // <---- NEW LINE
  riotee_gpio_cfg_output(TOGGLE_LED);
  // --->
}

// <---- NEW LINES
void turnoff_callback(void) {
  riotee_gpio_clear(TOGGLE_LED);
}
// --->

int main() {
  riotee_ble_adv_cfg_t adv_cfg = {.addr = adv_address,
                                  .name = adv_name,
                                  .name_len = 6,
                                  .data = &ble_data,
                                  .data_len = sizeof(ble_data),
                                  .manufacturer_id = RIOTEE_BLE_ADV_MNF_NORDIC};
  riotee_ble_adv_cfg(&adv_cfg);
  ble_data.counter = 0;
  for (;;) {
    riotee_wait_cap_charged();
    // <---- NEW LINE
    riotee_gpio_set(TOGGLE_LED);
    // --->

    riotee_ble_advertise(ADV_CH_ALL);
    ble_data.counter++;
    /* Sleep at least 250ms before next advertising round */
    riotee_sleep_ms(250);
  }
}
```

Compiled with Arduino IDE 2.2.1 + Riotee Board.

**Comment by geissdoerfer** [comment] 2024-01-19 15:54
The problem is the `turnoff_callback()`. This function was renamed to `suspend_callback()` with commit 8c3a794e87e5ab56a2a75ad87428e4772ba1d092. Please rename the function and close the issue if your application runs as expected.

**Comment by pbauszat** [comment] 2024-01-23 11:27
I upgraded to the newest version of the Riotee SDK (14/01/2024) and renamed to suspend_callback and unfortunately the problem still persists. Interestingly, I accidentally tried a version without the renaming which seemed to not dead-lock. I assume that in that case the code compiles but no callback is ever called on suspension in which case

`riotee_gpio_clear(TOGGLE_LED);`

is never called. Could be some indication that interaction with the GPIO during suspension seems to cause the dead-lock.

**Comment by geissdoerfer** [comment] 2024-01-23 19:59
OK, after fixing the turnoff_callback naming, your example seems to run fine when compiled with the SDK's makefile. The other problem is that you implement a `main()` and `reset_callback()` in an Arduino sketch. An Arduino sketch generally consists of two special functions `setup()` and `loop()`. I'm surprised that the Arduino IDE doesn't throw an exception when you try to implement the main function. Anyway, here's a version of your code adjusted to the Arduino API:

```
#include "riotee.h"
#include "riotee_ble.h"
#include "riotee_gpio.h"
#include "riotee_timing.h"

// <---- NEW LINE
#define TOGGLE_LED PIN_LED_CTRL
// --->

const uint8_t adv_address[] = {0x01, 0xEE, 0xC0, 0xFF, 0x03, 0x02};
const char adv_name[] = "RIOTEE";

static struct {
  unsigned int counter;
} ble_data;

void setup(void) {
  riotee_ble_init();
  // <---- NEW LINE
  riotee_gpio_cfg_output(TOGGLE_LED);
  // --->
  riotee_ble_adv_cfg_t adv_cfg = {.addr = adv_address,
                                  .name = adv_name,
                                  .name_len = 6,
                                  .data = &ble_data,
                                  .data_len = sizeof(ble_data),
                                  .manufacturer_id = RIOTEE_BLE_ADV_MNF_NORDIC};
  riotee_ble_adv_cfg(&adv_cfg);
  ble_data.counter = 0;
}

// <---- NEW LINES
void suspend_callback(void) {
  riotee_gpio_clear(TOGGLE_LED);
}
// --->

void loop() {

    riotee_wait_cap_charged();
    // <---- NEW LINE
    riotee_gpio_set(TOGGLE_LED);
    // --->

    riotee_ble_advertise(ADV_CH_ALL);
    ble_data.counter++;
    /* Sleep at least 250ms before next advertising round */
    riotee_sleep_ms(250);

}
```

Please close the issue if that works for you. I'll try to clarify this point in the documentation.

**Comment by pbauszat** [comment] 2024-02-01 10:48
I tried both the original code (with the suspend_callback fix) compiled in VS code and your proposed solution compiled with Arduino IDE. The problem remains either way.

I can reproduce this problem with different Riotee devices (so it does not seem to be just one broken probe), different light sources, and different capacitor settings (I tried the smallest 3, 4, 5). The LED keeps blinking a few times (somewhat unpredictable) and BLE packets are received at the scanner, but after a while the device seems to simple hang without blinking and no more packets arrive. Only a full device reset, will make the device working again for a few seconds. 

Do you have any suggestions how to debug this issue further?

**Comment by geissdoerfer** [comment] 2024-02-08 21:09
Thanks for following up with this. I just tried again with the Arduino sketch and the VSCode project and both run for minutes without problems on my setup. Let's try a few things:

## Debugging

The first thing I usually do to debug problems on Riotee is to attach an analog channel of a logic analyzer (or an oscilloscope) to the Vcap pin and monitor the capacitor voltage. I use a 1V constant power supply connected to Vin via a 1k resistor as a harvesting emulator as described [here](https://www.riotee.nessie-circuits.de/docs/latest/development_setup.html#power-supply). You may want to try that to avoid problems due to an inadequate power supply. It's probably best to start with a known working application like the blinky example. You should see a typical intermittent execution pattern like this:

![logic](https://github.com/NessieCircuits/Riotee_SDK/assets/13538910/f539de95-858b-48bf-9176-360c67fdf6b9)

Now when running your troubled application, watch out for the capacitor voltage dropping below around 2.5V. That indicates that something goes wrong.

## Reference code/binary

I've attached a zipped version of the vscode app that works on my setup: 
[VSCode_App.zip](https://github.com/NessieCircuits/Riotee_SDK/files/14214637/VSCode_App.zip)
 Please adjust the `.vscode/settings.json` according to your platform and try compiling and uploading the code.

I've also attached the Arduino sketch that works on my setup: 
[Arduino_sketch.zip](https://github.com/NessieCircuits/Riotee_SDK/files/14214632/Arduino_sketch.zip)
 Please give it a try.

Finally, I'm also attaching the binary hex that's just the compiled code from the vscode app [binary.hex.zip](https://github.com/NessieCircuits/Riotee_SDK/files/14214620/binary.hex.zip). Please unzip it and upload the hex to your board with `riotee-probe program -d nrf52 -f binary.hex`. Does that work?

## Arduino, SDK and compiler versions

Please send me the output of `arm-none-eabi-gcc --version`, the SDK version which you find under `/path/to/sdk/.bumpversion.cfg`and the version of the Arduino package which is displayed in the Arduino IDE's board manager. 


Let's hope we can get to the bottom of this!

**Comment by geissdoerfer** [comment] 2024-03-25 21:27
@pbauszat  Any update on this issue?

**Comment by geissdoerfer** [comment] 2024-05-09 16:32
I assume this issue has been resolved. Please reopen if not.

**Closed as completed by geissdoerfer** 2024-05-09 16:32 UTC
